import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
  en: {
    "Add to Home Screen": "Add to Home Screen",
    "To use Switch like a real app:": "To use Switch like a real app:",
    "iPhone (Safari): Tap the Share button → choose Add to Home Screen": "iPhone (Safari): Tap the <strong>Share</strong> button → choose <strong>Add to Home Screen</strong>.",
    "Android (Chrome): Tap the ⋮ menu → Add to Home screen": "Android (Chrome): Tap the <strong>⋮</strong> menu → <strong>Add to Home screen</strong>.",
    "OK": "OK",
    "Don't show again": "Don't show again",
    "Welcome to Switch!": "Welcome to Switch!",
    "Switch": "Switch",
    "Notifications": "Notifications",
    "Settings": "Settings",
    "Home": "Home",
    "Search": "Search",
    "Add": "Add",
    "Calendar": "Calendar",
    "Profile": "Profile",
    "Welcome to Switch! Feed": "Welcome to Switch!",
    "Start by adding dresses to your closet or discover other users to follow": "Start by adding dresses to your closet or discover other users to follow.",
    "Add Your First Dress": "Add Your First Dress",
    "Discover Users": "Discover Users",
    "per_day": "/day",
    "No image": "No image",
    "Search users, dresses, brands...": "Search users, dresses, brands...",
    "Users": "Users",
    "Dresses": "Dresses",
    "No users found matching your search": "No users found matching your search.",
    "No users to display yet": "No users to display yet.",
    "No dresses found matching your search": "No dresses found matching your search.",
    "No dresses to display yet": "No dresses to display yet.",
    "All Sizes": "All Sizes",
    "All Categories": "All Categories",
    "All Prices": "All Prices",
    "All Colors": "All Colors",
    "Size": "Size",
    "Category": "Category",
    "Price": "Price",
    "Color": "Color",
    "My Profile": "My Profile",
    "Edit Profile": "Edit Profile",
    "Profile updated successfully!": "Profile updated successfully!",
    "User Not Found": "User Not Found",
    "The profile you are looking for does not exist.": "The profile you are looking for does not exist.",
    "Go to Home": "Go to Home",
    "Followers": "Followers",
    "Following": "Following",
    "My Followers": "My Followers",
    "No followers yet": "No followers yet",
    "No following yet": "No following yet",
    "My Dresses": "My Dresses",
    "No dresses yet": "No dresses yet",
    "Add dress": "Add dress",
    "Add your first dress to start renting out your wardrobe": "Add your first dress to start renting out your wardrobe.",
    "This user hasn't added any dresses yet": "This user hasn't added any dresses yet.",
    "Rented": "Rented",
    "Follow": "Follow",
    "Unfollow": "Unfollow",
    "Following...": "Following...",
    "Unfollowing...": "Unfollowing...",
    "Contact": "Contact",
    "Contact {name}:": "Contact {name}:",
    "Instagram": "Instagram",
    "WhatsApp": "WhatsApp",
    "Email": "Email",
    "by {name}": "by {name}",
    "Add New Dress": "Add New Dress",
    "Photos": "Photos",
    "Add Photo": "Add Photo",
    "Add up to 5 photos. The first photo will be the cover image.": "Add up to 5 photos. The first photo will be the cover image.",
    "Dress Details": "Dress Details",
    "Dress Name *": "Dress Name *",
    "e.g., Black Evening Gown": "e.g., Black Evening Gown",
    "Description": "Description",
    "Describe the dress, occasion, fit, etc.": "Describe the dress, occasion, fit, etc.",
    "Size *": "Size *",
    "Select size": "Select size",
    "Price per Day *": "Price per Day *",
    "Select category": "Select category",
    "e.g., Black, Navy": "e.g., Black, Navy",
    "Brand": "Brand",
    "e.g., Zara, H&M": "e.g., Zara, H&M",
    "Add Dress to My Closet": "Add Dress to My Closet",
    "Adding Dress...": "Adding Dress...",
    "My Calendar": "My Calendar",
    "Add Rental": "Add Rental",
    "No dresses to track": "No dresses to track",
    "Add dresses to your closet first, then you can track their rental schedule": "Add dresses to your closet first, then you can track their rental schedule.",
    "No rentals scheduled for this date": "No rentals scheduled for this date.",
    "Schedule a Rental": "Schedule a Rental",
    "Public Info": "Public Info",
    "Full Name": "Full Name",
    "Your full name": "Your full name",
    "Bio": "Bio",
    "Tell others a little about yourself": "Tell others a little about yourself",
    "Country *": "Country *",
    "Select a country": "Select a country",
    "Pickup City *": "Pickup City *",
    "e.g., Tel Aviv": "e.g., Tel Aviv",
    "Contact Methods": "Contact Methods",
    "Instagram Handle": "Instagram Handle",
    "your_username": "your_username",
    "WhatsApp Number": "WhatsApp Number",
    "+972501234567": "+972501234567",
    "Contact Email": "Contact Email",
    "your.email@example.com": "your.email@example.com",
    "Save Changes": "Save Changes",
    "Saving Changes...": "Saving Changes...",
    "Failed to update profile. Please try again.": "Failed to update profile. Please try again.",
    "Pickup City is required.": "Pickup City is required.",
    "Complete Your Profile": "Complete Your Profile",
    "Let's set up your profile to get started with Switch": "Let's set up your profile to get started with Switch",
    "Add a profile photo (optional)": "Add a profile photo (optional)",
    "Basic Information": "Basic Information",
    "Full Name *": "Full Name *",
    "e.g., Tel Aviv, Jerusalem, Haifa": "e.g., Tel Aviv, Jerusalem, Haifa",
    "Where will people pick up dresses from you?": "Where will people pick up dresses from you?",
    "About You (Optional)": "About You (Optional)",
    "Tell others a little about yourself and your style...": "Tell others a little about yourself and your style...",
    "Choose at least one way for people to contact you about rentals": "Choose at least one way for people to contact you about rentals",
    "Please provide at least one contact method so others can reach you.": "Please provide at least one contact method so others can reach you.",
    "Save Profile & Continue": "Save Profile & Continue",
    "Saving Profile...": "Saving Profile...",
    "Please enter your full name.": "Please enter your full name.",
    "Please enter your pickup city.": "Please enter your pickup city.",
    "Please select your country.": "Please select your country.",
    "Please provide at least one contact method (Instagram, WhatsApp, or Email).": "Please provide at least one contact method (Instagram, WhatsApp, or Email).",
    "Failed to save profile. Please try again.": "Failed to save profile. Please try again.",
    "Profile Saved Successfully!": "Profile Saved Successfully!",
    "Welcome to Switch! You can now start exploring and sharing dresses.": "Welcome to Switch! You can now start exploring and sharing dresses.",
    "Redirecting to home...": "Redirecting to home...",
    "Evening": "Evening",
    "Cocktail": "Cocktail",
    "Casual": "Casual",
    "Formal": "Formal",
    "Wedding Guest": "Wedding Guest",
    "Party": "Party",
    "Work": "Work",
    "Other": "Other",
    "followers": "followers",
    "No image available": "No image available",
    "Country": "Country",
    "City": "City",
    "All Countries": "All Countries",
    "All Cities": "All Cities",
    "Clear Filters": "Clear Filters",
    "Are you sure?": "Are you sure?",
    "This will permanently delete this rental event. This action cannot be undone.": "This will permanently delete this rental event. This action cannot be undone.",
    "Delete": "Delete",
    "Cancel": "Cancel",
    "Deleting...": "Deleting..."
  },
  he: {
    "Add to Home Screen": "הוספה למסך הבית",
    "To use Switch like a real app:": "כדי להשתמש ב-Switch כמו אפליקציה אמיתית:",
    "iPhone (Safari): Tap the Share button → choose Add to Home Screen": "אייפון (ספארי): לחצו על כפתור ה-<strong>שיתוף</strong> → ובחרו <strong>הוסף למסך הבית</strong>.",
    "Android (Chrome): Tap the ⋮ menu → Add to Home screen": "אנדרואיד (כרום): לחצו על תפריט <strong>⋮</strong> → ובחרו <strong>הוסף למסך הבית</strong>.",
    "OK": "אישור",
    "Don't show again": "אל תציג שוב",
    "Welcome to Switch!": "ברוכים הבאים ל-Switch!",
    "Switch": "Switch",
    "Notifications": "התראות",
    "Settings": "הגדרות",
    "Home": "בית",
    "Search": "חיפוש",
    "Add": "הוספה",
    "Calendar": "יומן",
    "Profile": "פרופיל",
    "Welcome to Switch! Feed": "ברוכים הבאים ל-Switch!",
    "Start by adding dresses to your closet or discover other users to follow": "התחילו בהוספת שמלות לארון שלכן או גלו משתמשות אחרות לעקוב אחריהן.",
    "Add Your First Dress": "הוסיפי את השמלה הראשונה שלך",
    "Discover Users": "גלי משתמשות",
    "per_day": "/ליום",
    "No image": "אין תמונה",
    "Search users, dresses, brands...": "חפשי משתמשות, שמלות, מותגים...",
    "Users": "משתמשות",
    "Dresses": "שמלות",
    "No users found matching your search": "לא נמצאו משתמשות התואמות לחיפוש שלך.",
    "No users to display yet": "אין משתמשות להצגה עדיין.",
    "No dresses found matching your search": "לא נמצאו שמלות התואמות לחיפוש שלך.",
    "No dresses to display yet": "אין שמלות להצגה עדיין.",
    "All Sizes": "כל המידות",
    "All Categories": "כל הקטגוריות",
    "All Prices": "כל המחירים",
    "All Colors": "כל הצבעים",
    "Size": "מידה",
    "Category": "קטגוריה",
    "Price": "מחיר",
    "Color": "צבע",
    "My Profile": "הפרופיל שלי",
    "Edit Profile": "עריכת פרופיל",
    "Profile updated successfully!": "הפרופיל עודכן בהצלחה!",
    "User Not Found": "משתמשת לא נמצאה",
    "The profile you are looking for does not exist.": "הפרופיל שאת מחפשת לא קיים.",
    "Go to Home": "לדף הבית",
    "Followers": "עוקבות",
    "Following": "נעקבות",
    "My Followers": "העוקבות שלי",
    "No followers yet": "אין עוקבות עדיין",
    "No following yet": "לא עוקבת אחרי אף אחת עדיין",
    "My Dresses": "השמלות שלי",
    "No dresses yet": "אין שמלות עדיין",
    "Add dress": "הוסיפי שמלה",
    "Add your first dress to start renting out your wardrobe": "הוסיפי את השמלה הראשונה שלך כדי להתחיל להשכיר את המלתחה שלך.",
    "This user hasn't added any dresses yet": "משתמשת זו לא הוסיפה שמלות עדיין.",
    "Rented": "מושכרת",
    "Follow": "עקבי",
    "Unfollow": "הסירי עוקב",
    "Following...": "עוקבת...",
    "Unfollowing...": "מסירה עוקב...",
    "Contact": "יצירת קשר",
    "Contact {name}:": "צרי קשר עם {name}:",
    "Instagram": "אינסטגרם",
    "WhatsApp": "ווטסאפ",
    "Email": "אימייל",
    "by {name}": "מאת {name}",
    "Add New Dress": "הוספת שמלה חדשה",
    "Photos": "תמונות",
    "Add Photo": "הוסף תמונה",
    "Add up to 5 photos. The first photo will be the cover image.": "הוסיפי עד 5 תמונות. התמונה הראשונה תהיה תמונת הנושא.",
    "Dress Details": "פרטי השמלה",
    "Dress Name *": "שם השמלה *",
    "e.g., Black Evening Gown": "לדוגמה, שמלת ערב שחורה",
    "Description": "תיאור",
    "Describe the dress, occasion, fit, etc.": "תארי את השמלה, לאיזה אירוע, גזרה וכו'.",
    "Size *": "מידה *",
    "Select size": "בחרי מידה",
    "Price per Day *": "מחיר ליום *",
    "Select category": "בחרי קטגוריה",
    "e.g., Black, Navy": "לדוגמה, שחור, כחול כהה",
    "Brand": "מותג",
    "e.g., Zara, H&M": "לדוגמה, זארה, H&M",
    "Add Dress to My Closet": "הוסיפי שמלה לארון שלי",
    "Adding Dress...": "מוסיפה שמלה...",
    "My Calendar": "היומן שלי",
    "Add Rental": "הוספת השכרה",
    "No dresses to track": "אין שמלות למעקב",
    "Add dresses to your closet first, then you can track their rental schedule": "הוסיפי שמלות לארון שלך ואז תוכלי לעקוב אחר לוח ההשכרות שלהן.",
    "No rentals scheduled for this date": "אין השכרות מתוכננות לתאריך זה.",
    "Schedule a Rental": "תכנני השכרה",
    "Public Info": "מידע ציבורי",
    "Full Name": "שם מלא",
    "Your full name": "השם המלא שלך",
    "Bio": "ביו",
    "Tell others a little about yourself": "ספרי לאחרות קצת על עצמך",
    "Country *": "מדינה *",
    "Select a country": "בחרי מדינה",
    "Pickup City *": "עיר איסוף *",
    "e.g., Tel Aviv": "לדוגמה, תל אביב",
    "Contact Methods": "דרכי התקשרות",
    "Instagram Handle": "שם משתמש באינסטגרם",
    "your_username": "your_username",
    "WhatsApp Number": "מספר ווטסאפ",
    "+972501234567": "+972501234567",
    "Contact Email": "כתובת אימייל ליצירת קשר",
    "your.email@example.com": "your.email@example.com",
    "Save Changes": "שמירת שינויים",
    "Saving Changes...": "שומרת שינויים...",
    "Failed to update profile. Please try again.": "עדכון הפרופיל נכשל. אנא נסי שוב.",
    "Pickup City is required.": "נדרש למלא עיר איסוף.",
    "Complete Your Profile": "השלימי את הפרופיל שלך",
    "Let's set up your profile to get started with Switch": "בואי נגדיר את הפרופיל שלך כדי להתחיל להשתמש ב-Switch",
    "Add a profile photo (optional)": "הוסיפי תמונת פרופיל (אופציונלי)",
    "Basic Information": "מידע בסיסי",
    "Full Name *": "שם מלא *",
    "e.g., Tel Aviv, Jerusalem, Haifa": "לדוגמה, תל אביב, ירושלים, חיפה",
    "Where will people pick up dresses from you?": "היכן אנשים יאספו ממך שמלות?",
    "About You (Optional)": "על עצמך (אופציונלי)",
    "Tell others a little about yourself and your style...": "ספרי לאחרות קצת על עצמך ועל הסגנון שלך...",
    "Choose at least one way for people to contact you about rentals": "בחרי לפחות דרך אחת שבה יוכלו ליצור איתך קשר לגבי השכרות",
    "Please provide at least one contact method so others can reach you.": "אנא ספקי לפחות דרך אחת ליצירת קשר כדי שאחרות יוכלו להשיג אותך.",
    "Save Profile & Continue": "שמרי פרופיל והמשיכי",
    "Saving Profile...": "שומרת פרופיל...",
    "Please enter your full name.": "אנא הזיני את שמך המלא.",
    "Please enter your pickup city.": "אנא הזיני את עיר האיסוף שלך.",
    "Please select your country.": "אנא בחרי את המדינה שלך.",
    "Please provide at least one contact method (Instagram, WhatsApp, or Email).": "אנא ספקי לפחות אמצעי קשר אחד (אינסטגרם, ווטסאפ או אימייל).",
    "Failed to save profile. Please try again.": "שמירת הפרופיל נכשלה. אנא נסי שוב.",
    "Profile Saved Successfully!": "הפרופיל נשמר בהצלחה!",
    "Welcome to Switch! You can now start exploring and sharing dresses.": "ברוכה הבאה ל-Switch! עכשיו תוכלי להתחיל לחקור ולשתף שמלות.",
    "Redirecting to home...": "מעבירה אותך לדף הבית...",
    "Evening": "ערב",
    "Cocktail": "קוקטייל",
    "Casual": "יומיומי",
    "Formal": "רשמי",
    "Wedding Guest": "אורחת בחתונה",
    "Party": "מסיבה",
    "Work": "עבודה",
    "Other": "אחר",
    "followers": "עוקבות",
    "No image available": "אין תמונה זמינה",
    "Country": "מדינה",
    "City": "עיר",
    "All Countries": "כל המדינות",
    "All Cities": "כל הערים",
    "Clear Filters": "נקי מסננים",
    "Are you sure?": "האם את בטוחה?",
    "This will permanently delete this rental event. This action cannot be undone.": "פעולה זו תמחק את אירוע ההשכרה לצמיתות. לא ניתן לבטל פעולה זו.",
    "Delete": "מחק",
    "Cancel": "ביטול",
    "Deleting...": "מוחקת..."
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    const browserLang = navigator.language.split('-')[0];
    const initialLang = savedLang || (translations[browserLang] ? browserLang : 'en');
    setLanguage(initialLang);
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || key;
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);